"""Settings for Milestone 2. Change these values to configure organisms and energy."""

INITIAL_ORGANISM_ENERGY = 100.0
MAX_ORGANISM_ENERGY = 100.0
INITIAL_ORGANISM_HEALTH = 100.0
MAX_ORGANISM_HEALTH = 100.0
INITIAL_ENERGY_RESOURCE = 500.0
MAX_ENERGY_RESOURCE = 500.0
MAX_ENERGY_INTAKE = 20.0
